//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("NhaHangHanModel", "FK_CTDH_HoaDon", "HoaDon", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AppQuanLyNhaHang.HoaDon), "CTDH", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AppQuanLyNhaHang.CTDH), true)]
[assembly: EdmRelationshipAttribute("NhaHangHanModel", "FK_CTDH_SanPham", "SanPham", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AppQuanLyNhaHang.SanPham), "CTDH", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AppQuanLyNhaHang.CTDH), true)]
[assembly: EdmRelationshipAttribute("NhaHangHanModel", "FK_HoaDon_KhachHang", "KhachHang", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AppQuanLyNhaHang.KhachHang), "HoaDon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AppQuanLyNhaHang.HoaDon), true)]
[assembly: EdmRelationshipAttribute("NhaHangHanModel", "FK_HoaDon_NhanVien", "NhanVien", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AppQuanLyNhaHang.NhanVien), "HoaDon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AppQuanLyNhaHang.HoaDon), true)]
[assembly: EdmRelationshipAttribute("NhaHangHanModel", "FK_SanPham_LoaiSP", "LoaiSP", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AppQuanLyNhaHang.LoaiSP), "SanPham", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AppQuanLyNhaHang.SanPham), true)]

#endregion

namespace AppQuanLyNhaHang
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NhaHangHanEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NhaHangHanEntities object using the connection string found in the 'NhaHangHanEntities' section of the application configuration file.
        /// </summary>
        public NhaHangHanEntities() : base("name=NhaHangHanEntities", "NhaHangHanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NhaHangHanEntities object.
        /// </summary>
        public NhaHangHanEntities(string connectionString) : base(connectionString, "NhaHangHanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NhaHangHanEntities object.
        /// </summary>
        public NhaHangHanEntities(EntityConnection connection) : base(connection, "NhaHangHanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CTDH> CTDH
        {
            get
            {
                if ((_CTDH == null))
                {
                    _CTDH = base.CreateObjectSet<CTDH>("CTDH");
                }
                return _CTDH;
            }
        }
        private ObjectSet<CTDH> _CTDH;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HoaDon> HoaDon
        {
            get
            {
                if ((_HoaDon == null))
                {
                    _HoaDon = base.CreateObjectSet<HoaDon>("HoaDon");
                }
                return _HoaDon;
            }
        }
        private ObjectSet<HoaDon> _HoaDon;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KhachHang> KhachHang
        {
            get
            {
                if ((_KhachHang == null))
                {
                    _KhachHang = base.CreateObjectSet<KhachHang>("KhachHang");
                }
                return _KhachHang;
            }
        }
        private ObjectSet<KhachHang> _KhachHang;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LoaiSP> LoaiSP
        {
            get
            {
                if ((_LoaiSP == null))
                {
                    _LoaiSP = base.CreateObjectSet<LoaiSP>("LoaiSP");
                }
                return _LoaiSP;
            }
        }
        private ObjectSet<LoaiSP> _LoaiSP;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NhanVien> NhanVien
        {
            get
            {
                if ((_NhanVien == null))
                {
                    _NhanVien = base.CreateObjectSet<NhanVien>("NhanVien");
                }
                return _NhanVien;
            }
        }
        private ObjectSet<NhanVien> _NhanVien;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SanPham> SanPham
        {
            get
            {
                if ((_SanPham == null))
                {
                    _SanPham = base.CreateObjectSet<SanPham>("SanPham");
                }
                return _SanPham;
            }
        }
        private ObjectSet<SanPham> _SanPham;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CTDH EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCTDH(CTDH cTDH)
        {
            base.AddObject("CTDH", cTDH);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HoaDon EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHoaDon(HoaDon hoaDon)
        {
            base.AddObject("HoaDon", hoaDon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KhachHang EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKhachHang(KhachHang khachHang)
        {
            base.AddObject("KhachHang", khachHang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoaiSP EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoaiSP(LoaiSP loaiSP)
        {
            base.AddObject("LoaiSP", loaiSP);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NhanVien EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNhanVien(NhanVien nhanVien)
        {
            base.AddObject("NhanVien", nhanVien);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SanPham EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSanPham(SanPham sanPham)
        {
            base.AddObject("SanPham", sanPham);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NhaHangHanModel", Name="CTDH")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CTDH : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CTDH object.
        /// </summary>
        /// <param name="maHD">Initial value of the MaHD property.</param>
        /// <param name="maSP">Initial value of the MaSP property.</param>
        public static CTDH CreateCTDH(global::System.Int32 maHD, global::System.String maSP)
        {
            CTDH cTDH = new CTDH();
            cTDH.MaHD = maHD;
            cTDH.MaSP = maSP;
            return cTDH;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaHD
        {
            get
            {
                return _MaHD;
            }
            set
            {
                if (_MaHD != value)
                {
                    OnMaHDChanging(value);
                    ReportPropertyChanging("MaHD");
                    _MaHD = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaHD");
                    OnMaHDChanged();
                }
            }
        }
        private global::System.Int32 _MaHD;
        partial void OnMaHDChanging(global::System.Int32 value);
        partial void OnMaHDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaSP
        {
            get
            {
                return _MaSP;
            }
            set
            {
                if (_MaSP != value)
                {
                    OnMaSPChanging(value);
                    ReportPropertyChanging("MaSP");
                    _MaSP = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaSP");
                    OnMaSPChanged();
                }
            }
        }
        private global::System.String _MaSP;
        partial void OnMaSPChanging(global::System.String value);
        partial void OnMaSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Soluong
        {
            get
            {
                return _Soluong;
            }
            set
            {
                OnSoluongChanging(value);
                ReportPropertyChanging("Soluong");
                _Soluong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Soluong");
                OnSoluongChanged();
            }
        }
        private Nullable<global::System.Int16> _Soluong;
        partial void OnSoluongChanging(Nullable<global::System.Int16> value);
        partial void OnSoluongChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NhaHangHanModel", "FK_CTDH_HoaDon", "HoaDon")]
        public HoaDon HoaDon
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoaDon>("NhaHangHanModel.FK_CTDH_HoaDon", "HoaDon").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoaDon>("NhaHangHanModel.FK_CTDH_HoaDon", "HoaDon").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HoaDon> HoaDonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoaDon>("NhaHangHanModel.FK_CTDH_HoaDon", "HoaDon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HoaDon>("NhaHangHanModel.FK_CTDH_HoaDon", "HoaDon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NhaHangHanModel", "FK_CTDH_SanPham", "SanPham")]
        public SanPham SanPham
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SanPham>("NhaHangHanModel.FK_CTDH_SanPham", "SanPham").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SanPham>("NhaHangHanModel.FK_CTDH_SanPham", "SanPham").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SanPham> SanPhamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SanPham>("NhaHangHanModel.FK_CTDH_SanPham", "SanPham");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SanPham>("NhaHangHanModel.FK_CTDH_SanPham", "SanPham", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NhaHangHanModel", Name="HoaDon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HoaDon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HoaDon object.
        /// </summary>
        /// <param name="maHD">Initial value of the MaHD property.</param>
        public static HoaDon CreateHoaDon(global::System.Int32 maHD)
        {
            HoaDon hoaDon = new HoaDon();
            hoaDon.MaHD = maHD;
            return hoaDon;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaHD
        {
            get
            {
                return _MaHD;
            }
            set
            {
                if (_MaHD != value)
                {
                    OnMaHDChanging(value);
                    ReportPropertyChanging("MaHD");
                    _MaHD = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaHD");
                    OnMaHDChanged();
                }
            }
        }
        private global::System.Int32 _MaHD;
        partial void OnMaHDChanging(global::System.Int32 value);
        partial void OnMaHDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaKH
        {
            get
            {
                return _MaKH;
            }
            set
            {
                OnMaKHChanging(value);
                ReportPropertyChanging("MaKH");
                _MaKH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaKH");
                OnMaKHChanged();
            }
        }
        private Nullable<global::System.Int32> _MaKH;
        partial void OnMaKHChanging(Nullable<global::System.Int32> value);
        partial void OnMaKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaNV
        {
            get
            {
                return _MaNV;
            }
            set
            {
                OnMaNVChanging(value);
                ReportPropertyChanging("MaNV");
                _MaNV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaNV");
                OnMaNVChanged();
            }
        }
        private Nullable<global::System.Int32> _MaNV;
        partial void OnMaNVChanging(Nullable<global::System.Int32> value);
        partial void OnMaNVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayLapHD
        {
            get
            {
                return _NgayLapHD;
            }
            set
            {
                OnNgayLapHDChanging(value);
                ReportPropertyChanging("NgayLapHD");
                _NgayLapHD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgayLapHD");
                OnNgayLapHDChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayLapHD;
        partial void OnNgayLapHDChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayLapHDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NhaHangHanModel", "FK_CTDH_HoaDon", "CTDH")]
        public EntityCollection<CTDH> CTDH
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CTDH>("NhaHangHanModel.FK_CTDH_HoaDon", "CTDH");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CTDH>("NhaHangHanModel.FK_CTDH_HoaDon", "CTDH", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NhaHangHanModel", "FK_HoaDon_KhachHang", "KhachHang")]
        public KhachHang KhachHang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("NhaHangHanModel.FK_HoaDon_KhachHang", "KhachHang").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("NhaHangHanModel.FK_HoaDon_KhachHang", "KhachHang").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<KhachHang> KhachHangReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("NhaHangHanModel.FK_HoaDon_KhachHang", "KhachHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<KhachHang>("NhaHangHanModel.FK_HoaDon_KhachHang", "KhachHang", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NhaHangHanModel", "FK_HoaDon_NhanVien", "NhanVien")]
        public NhanVien NhanVien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhanVien>("NhaHangHanModel.FK_HoaDon_NhanVien", "NhanVien").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhanVien>("NhaHangHanModel.FK_HoaDon_NhanVien", "NhanVien").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NhanVien> NhanVienReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhanVien>("NhaHangHanModel.FK_HoaDon_NhanVien", "NhanVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NhanVien>("NhaHangHanModel.FK_HoaDon_NhanVien", "NhanVien", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NhaHangHanModel", Name="KhachHang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KhachHang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KhachHang object.
        /// </summary>
        /// <param name="maKH">Initial value of the MaKH property.</param>
        public static KhachHang CreateKhachHang(global::System.Int32 maKH)
        {
            KhachHang khachHang = new KhachHang();
            khachHang.MaKH = maKH;
            return khachHang;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaKH
        {
            get
            {
                return _MaKH;
            }
            set
            {
                if (_MaKH != value)
                {
                    OnMaKHChanging(value);
                    ReportPropertyChanging("MaKH");
                    _MaKH = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaKH");
                    OnMaKHChanged();
                }
            }
        }
        private global::System.Int32 _MaKH;
        partial void OnMaKHChanging(global::System.Int32 value);
        partial void OnMaKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoKH
        {
            get
            {
                return _HoKH;
            }
            set
            {
                OnHoKHChanging(value);
                ReportPropertyChanging("HoKH");
                _HoKH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HoKH");
                OnHoKHChanged();
            }
        }
        private global::System.String _HoKH;
        partial void OnHoKHChanging(global::System.String value);
        partial void OnHoKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenKH
        {
            get
            {
                return _TenKH;
            }
            set
            {
                OnTenKHChanging(value);
                ReportPropertyChanging("TenKH");
                _TenKH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenKH");
                OnTenKHChanged();
            }
        }
        private global::System.String _TenKH;
        partial void OnTenKHChanging(global::System.String value);
        partial void OnTenKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Ngaysinh
        {
            get
            {
                return _Ngaysinh;
            }
            set
            {
                OnNgaysinhChanging(value);
                ReportPropertyChanging("Ngaysinh");
                _Ngaysinh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ngaysinh");
                OnNgaysinhChanged();
            }
        }
        private Nullable<global::System.DateTime> _Ngaysinh;
        partial void OnNgaysinhChanging(Nullable<global::System.DateTime> value);
        partial void OnNgaysinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Diachi
        {
            get
            {
                return _Diachi;
            }
            set
            {
                OnDiachiChanging(value);
                ReportPropertyChanging("Diachi");
                _Diachi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Diachi");
                OnDiachiChanged();
            }
        }
        private global::System.String _Diachi;
        partial void OnDiachiChanging(global::System.String value);
        partial void OnDiachiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dienthoai
        {
            get
            {
                return _Dienthoai;
            }
            set
            {
                OnDienthoaiChanging(value);
                ReportPropertyChanging("Dienthoai");
                _Dienthoai = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dienthoai");
                OnDienthoaiChanged();
            }
        }
        private global::System.String _Dienthoai;
        partial void OnDienthoaiChanging(global::System.String value);
        partial void OnDienthoaiChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NhaHangHanModel", "FK_HoaDon_KhachHang", "HoaDon")]
        public EntityCollection<HoaDon> HoaDon
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HoaDon>("NhaHangHanModel.FK_HoaDon_KhachHang", "HoaDon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HoaDon>("NhaHangHanModel.FK_HoaDon_KhachHang", "HoaDon", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NhaHangHanModel", Name="LoaiSP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoaiSP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LoaiSP object.
        /// </summary>
        /// <param name="maLoaiSP">Initial value of the MaLoaiSP property.</param>
        public static LoaiSP CreateLoaiSP(global::System.Int32 maLoaiSP)
        {
            LoaiSP loaiSP = new LoaiSP();
            loaiSP.MaLoaiSP = maLoaiSP;
            return loaiSP;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaLoaiSP
        {
            get
            {
                return _MaLoaiSP;
            }
            set
            {
                if (_MaLoaiSP != value)
                {
                    OnMaLoaiSPChanging(value);
                    ReportPropertyChanging("MaLoaiSP");
                    _MaLoaiSP = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaLoaiSP");
                    OnMaLoaiSPChanged();
                }
            }
        }
        private global::System.Int32 _MaLoaiSP;
        partial void OnMaLoaiSPChanging(global::System.Int32 value);
        partial void OnMaLoaiSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenLoaiSP
        {
            get
            {
                return _TenLoaiSP;
            }
            set
            {
                OnTenLoaiSPChanging(value);
                ReportPropertyChanging("TenLoaiSP");
                _TenLoaiSP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenLoaiSP");
                OnTenLoaiSPChanged();
            }
        }
        private global::System.String _TenLoaiSP;
        partial void OnTenLoaiSPChanging(global::System.String value);
        partial void OnTenLoaiSPChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NhaHangHanModel", "FK_SanPham_LoaiSP", "SanPham")]
        public EntityCollection<SanPham> SanPham
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SanPham>("NhaHangHanModel.FK_SanPham_LoaiSP", "SanPham");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SanPham>("NhaHangHanModel.FK_SanPham_LoaiSP", "SanPham", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NhaHangHanModel", Name="NhanVien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NhanVien : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NhanVien object.
        /// </summary>
        /// <param name="maNV">Initial value of the MaNV property.</param>
        public static NhanVien CreateNhanVien(global::System.Int32 maNV)
        {
            NhanVien nhanVien = new NhanVien();
            nhanVien.MaNV = maNV;
            return nhanVien;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaNV
        {
            get
            {
                return _MaNV;
            }
            set
            {
                if (_MaNV != value)
                {
                    OnMaNVChanging(value);
                    ReportPropertyChanging("MaNV");
                    _MaNV = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaNV");
                    OnMaNVChanged();
                }
            }
        }
        private global::System.Int32 _MaNV;
        partial void OnMaNVChanging(global::System.Int32 value);
        partial void OnMaNVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoNV
        {
            get
            {
                return _HoNV;
            }
            set
            {
                OnHoNVChanging(value);
                ReportPropertyChanging("HoNV");
                _HoNV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HoNV");
                OnHoNVChanged();
            }
        }
        private global::System.String _HoNV;
        partial void OnHoNVChanging(global::System.String value);
        partial void OnHoNVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenNV
        {
            get
            {
                return _TenNV;
            }
            set
            {
                OnTenNVChanging(value);
                ReportPropertyChanging("TenNV");
                _TenNV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenNV");
                OnTenNVChanged();
            }
        }
        private global::System.String _TenNV;
        partial void OnTenNVChanging(global::System.String value);
        partial void OnTenNVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgaysinhNV
        {
            get
            {
                return _NgaysinhNV;
            }
            set
            {
                OnNgaysinhNVChanging(value);
                ReportPropertyChanging("NgaysinhNV");
                _NgaysinhNV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgaysinhNV");
                OnNgaysinhNVChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgaysinhNV;
        partial void OnNgaysinhNVChanging(Nullable<global::System.DateTime> value);
        partial void OnNgaysinhNVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Diachi
        {
            get
            {
                return _Diachi;
            }
            set
            {
                OnDiachiChanging(value);
                ReportPropertyChanging("Diachi");
                _Diachi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Diachi");
                OnDiachiChanged();
            }
        }
        private global::System.String _Diachi;
        partial void OnDiachiChanging(global::System.String value);
        partial void OnDiachiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dienthoai
        {
            get
            {
                return _Dienthoai;
            }
            set
            {
                OnDienthoaiChanging(value);
                ReportPropertyChanging("Dienthoai");
                _Dienthoai = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dienthoai");
                OnDienthoaiChanged();
            }
        }
        private global::System.String _Dienthoai;
        partial void OnDienthoaiChanging(global::System.String value);
        partial void OnDienthoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Chucvu
        {
            get
            {
                return _Chucvu;
            }
            set
            {
                OnChucvuChanging(value);
                ReportPropertyChanging("Chucvu");
                _Chucvu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Chucvu");
                OnChucvuChanged();
            }
        }
        private global::System.String _Chucvu;
        partial void OnChucvuChanging(global::System.String value);
        partial void OnChucvuChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NhaHangHanModel", "FK_HoaDon_NhanVien", "HoaDon")]
        public EntityCollection<HoaDon> HoaDon
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HoaDon>("NhaHangHanModel.FK_HoaDon_NhanVien", "HoaDon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HoaDon>("NhaHangHanModel.FK_HoaDon_NhanVien", "HoaDon", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NhaHangHanModel", Name="SanPham")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SanPham : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SanPham object.
        /// </summary>
        /// <param name="maSP">Initial value of the MaSP property.</param>
        /// <param name="maLoaiSP">Initial value of the MaLoaiSP property.</param>
        public static SanPham CreateSanPham(global::System.String maSP, global::System.Int32 maLoaiSP)
        {
            SanPham sanPham = new SanPham();
            sanPham.MaSP = maSP;
            sanPham.MaLoaiSP = maLoaiSP;
            return sanPham;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaSP
        {
            get
            {
                return _MaSP;
            }
            set
            {
                if (_MaSP != value)
                {
                    OnMaSPChanging(value);
                    ReportPropertyChanging("MaSP");
                    _MaSP = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaSP");
                    OnMaSPChanged();
                }
            }
        }
        private global::System.String _MaSP;
        partial void OnMaSPChanging(global::System.String value);
        partial void OnMaSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenSP
        {
            get
            {
                return _TenSP;
            }
            set
            {
                OnTenSPChanging(value);
                ReportPropertyChanging("TenSP");
                _TenSP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenSP");
                OnTenSPChanged();
            }
        }
        private global::System.String _TenSP;
        partial void OnTenSPChanging(global::System.String value);
        partial void OnTenSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Donvitinh
        {
            get
            {
                return _Donvitinh;
            }
            set
            {
                OnDonvitinhChanging(value);
                ReportPropertyChanging("Donvitinh");
                _Donvitinh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Donvitinh");
                OnDonvitinhChanged();
            }
        }
        private global::System.String _Donvitinh;
        partial void OnDonvitinhChanging(global::System.String value);
        partial void OnDonvitinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Dongia
        {
            get
            {
                return _Dongia;
            }
            set
            {
                OnDongiaChanging(value);
                ReportPropertyChanging("Dongia");
                _Dongia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dongia");
                OnDongiaChanged();
            }
        }
        private Nullable<global::System.Double> _Dongia;
        partial void OnDongiaChanging(Nullable<global::System.Double> value);
        partial void OnDongiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaLoaiSP
        {
            get
            {
                return _MaLoaiSP;
            }
            set
            {
                OnMaLoaiSPChanging(value);
                ReportPropertyChanging("MaLoaiSP");
                _MaLoaiSP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaLoaiSP");
                OnMaLoaiSPChanged();
            }
        }
        private global::System.Int32 _MaLoaiSP;
        partial void OnMaLoaiSPChanging(global::System.Int32 value);
        partial void OnMaLoaiSPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HinhSP
        {
            get
            {
                return _HinhSP;
            }
            set
            {
                OnHinhSPChanging(value);
                ReportPropertyChanging("HinhSP");
                _HinhSP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HinhSP");
                OnHinhSPChanged();
            }
        }
        private global::System.String _HinhSP;
        partial void OnHinhSPChanging(global::System.String value);
        partial void OnHinhSPChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NhaHangHanModel", "FK_CTDH_SanPham", "CTDH")]
        public EntityCollection<CTDH> CTDH
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CTDH>("NhaHangHanModel.FK_CTDH_SanPham", "CTDH");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CTDH>("NhaHangHanModel.FK_CTDH_SanPham", "CTDH", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NhaHangHanModel", "FK_SanPham_LoaiSP", "LoaiSP")]
        public LoaiSP LoaiSP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiSP>("NhaHangHanModel.FK_SanPham_LoaiSP", "LoaiSP").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiSP>("NhaHangHanModel.FK_SanPham_LoaiSP", "LoaiSP").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LoaiSP> LoaiSPReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiSP>("NhaHangHanModel.FK_SanPham_LoaiSP", "LoaiSP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LoaiSP>("NhaHangHanModel.FK_SanPham_LoaiSP", "LoaiSP", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
